### ISSUE TITLE
[Error] 'st_face' object has no attribute 'selective_search_roidb'

### ISSUE THREAD

**Issue by caseyanya** [kensun0/Face-Detecion-with-the-Faster-R-CNN-R-FCN#1]
Hi, kensun0
I really appreciate your work, but there's a bit error I can't deal with. 
When I start training, I got this error:
AttributeError: 'st_face' object has no attribute 'selective_search_roidb'
I build my environment with the guide of rbg in py-faster-rcnn. 
Then copy your files into corresponding path. 
I also modified these 2 paths in st_face.py to my own path. 
***
f = h5py.File('/data/st/data/wider/wider_face_train.mat')
prefix='/data/st/data/wider/train/'
***
Here is how my wider dataset looks like

$ RCNN_root/data
------------------------/wider
------------------------/wider/wider_face_train.mat
------------------------/wider/wider_face_val.mat
------------------------/wider/train    #extract from WIDER_train.zip(official download)
------------------------/wider/val      #extract from WIDER_val.zip(official download)

Is there any solution to this error?
Thanks. 

--- Full Log Here---
Called with args:
Namespace(cfg_file='experiments/cfgs/faster_rcnn_end2end.yml', gpu_id=0, imdb_name='st_face', max_iters=10000, pretrained_model='vgg16_faster_rcnn_final.caffemodel', randomize=False, set_cfgs=None, solver='models/pascal_voc/VGG16/faster_rcnn_end2end/solver.prototxt')
Using config:
{'DATA_DIR': '/home/caffe1/rcnn_face_kensun0/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'faster_rcnn_end2end',
 'GPU_ID': 0,
 'MATLAB': 'matlab',
 'MODELS_DIR': '/home/caffe1/rcnn_face_kensun0/models/pascal_voc',
 'PIXEL_MEANS': array([[[ 102.9801,  115.9465,  122.7717]]]),
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/caffe1/rcnn_face_kensun0',
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'selective_search',
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': True,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'MAX_SIZE': 1000,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 16,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_INFIX': '',
           'SNAPSHOT_ITERS': 10000,
           'USE_FLIPPED': True,
           'USE_PREFETCH': False},
 'USE_GPU_NMS': True}
Loaded dataset `st_face` for training
Traceback (most recent call last):
  File "./tools/train_net.py", line 104, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/train_net.py", line 69, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/train_net.py", line 64, in get_roidb
    imdb.set_proposal_method(cfg.TRAIN.PROPOSAL_METHOD)
  File "/home/caffe1/rcnn_face_kensun0/tools/../lib/datasets/imdb.py", line 55, in set_proposal_method
    method = eval('self.' + method + '_roidb')
  File "<string>", line 1, in <module>
AttributeError: 'st_face' object has no attribute 'selective_search_roidb'

**Comment by kensun0** [comment]
there is no "selective_search_roidb" function in st_face.py, only "gt_roidb".
imdb.set_proposal_method(cfg.TRAIN.PROPOSAL_METHOD) should be "gt", not "selective_search".
Maybe you shuold change PROPOSAL_METHOD="gt" in your cfg_file='experiments/cfgs/faster_rcnn_end2end.yml'
Or, you can impletemnet "selective_search_roidb" funciton according to pascal_voc.py

**Comment by caseyanya** [comment]
Thanks for your reply. 
It is already PROPOSAL_METHOD="gt" in my faster_rcnn_end2end.yml. 
Is there any other possibility?

**Comment by kensun0** [comment]
i do not know why.
you should trace you code to find why proposal_method is "selective_search".

**Comment by caseyanya** [comment]
Thanks a lot!!!
I found the point I was missing. 
I modified line92 in " lib/fast_rcnn/config.py " to __C.TRAIN.PROPOSAL_METHOD = 'gt'
It solves the error. 
Sorry about that I'm new in caffe.

**Comment by kensun0** [comment]
you are welcome
have fun~
