### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by vitoralbiero** [kensun0/Face-Detecion-with-the-Faster-R-CNN-R-FCN#2]
Hello Kensun, I want to know if the code you provide in this repo is the same from this paper: https://arxiv.org/abs/1606.03473

If not, what did you modified in the VGG16 network?

Thank you!!!

**Comment by kensun0** [comment]
i do not follow the original paper, but i get the same result almost.
you can check my prototxt in this repo to find my modification.
here is it, /models/pascal_voc/VGG16/faster_rcnn_end2end/train.prototxt

**Comment by vitoralbiero** [comment]
Okay, I am getting good results with your modifications.

Do you have a paper that I can cite when using your code for preprossing the images for a paper that I am working on?

**Comment by vitoralbiero** [comment]
Nevermind, I am going to use the default network, thank you!
